config/routes.rb
Rails.application.routes.draw do
  get 'bookings/new'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Adding an 'about' controller method
  resources :flats do
    resources :bookings, only: %i[create edit update]
  end
  resources :bookings, only: [:destroy] do
    resources :reviews, only: %i[new create]
  end
  resources :reviews, only: [:destroy]
  # Defines the root path route ("/")
  # root "articles#index"
  get    "pages/my_flats", to: "pages#my_flats", as: :my_flats
  get    "pages/my_bookings", to: "pages#my_bookings", as: :my_bookings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :flat
  has_one :review, dependent: :destroy

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :adults, :children, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validate :end_date_after_start_date

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    errors.add(:end_date, "must be after the start date") if end_date < start_date
  end
end

app/models/flat.rb
class Flat < ApplicationRecord
  has_one_attached :photo
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings

  validates :name, presence: true, uniqueness: true
  validates :rooms, :price, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_name_address_description,
                  against: [ :name, :description, :address ],
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking

  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar
  has_many :flats
  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user! # devise stuff
  include Pundit::Authorization

  # Pundit: allow-list approach - "destroy every single page of our app!!"
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
  # For additional fields in app/views/devise/registrations/new.html.erb
  devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :avatar])

  # For additional in app/views/devise/registrations/edit.html.erb
  devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :avatar])
  end

  # LeWagon (warning message) Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:destroy]
  before_action :set_flat, only: %i[new create edit update]

  def create
    @booking = Booking.new(booking_params)
    authorize @booking
    @booking.flat = @flat
    @booking.user = current_user
    if @booking.valid?
      @booking.save!
      redirect_to my_bookings_path
      flash[:notice] = 'Your booking is saved!'
    else
      redirect_to flat_path(@flat)
      flash[:alert] = 'Please introduce a start date and end date'
    end
  end

  def edit
  end

  def update
    @booking.update(booking_params)

    redirect_to my_bookings_path
    # waiting for show page to fix redirect, and maybe write a conditional estatement
  end

  def destroy
    @booking.destroy
    redirect_to my_bookings_path(@booking), status: :see_other
    # redirect_to my_bookings_path(@booking), notice: "Booking reservation was been cancelled"
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :adults, :children)
  end

  def set_booking
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def set_flat
    @flat = Flat.find(params[:flat_id])
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    if params[:query].present?
      @flats = policy_scope(Flat).search_by_name_address_description(params[:query])
      if @flats.empty?
        flash[:alert] = "No results found. Displaying all flats instead"
        @flats = policy_scope(Flat)
      end
    else
      @flats = policy_scope(Flat) # adding bundit stuff, "policy_scope()"
    end
    # geocoding stuff, scope filters only flats with coordinates
    @markers = @flats.geocoded.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { flat: })
        # marker_html: render_to_string(partial: "marker") - if we want to change the marker, go to _marker.html.erb shared/view
        # marker_html: render_to_string(partial: "marker", clocals: {flat: flat}) - add info to the marker from the _marker.html.erb file
      }
    end
  end

  def new
    @flat = Flat.new
    authorize @flat # pundit stuff
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.user = current_user

    authorize @flat # pundit stuff

    if @flat.save!
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def show
    @booking = Booking.new
    @bookings = @flat.bookings
    authorize @booking
    @markers = [{
      lat: @flat.latitude,
      lng: @flat.longitude,
      info_window_html: render_to_string(partial: "info_window", locals: { flat: @flat })
      # marker_html: render_to_string(partial: "marker") - if we want to change the marker, go to _marker.html.erb shared/view
      # marker_html: render_to_string(partial: "marker", clocals: {flat: flat}) - add info to the marker from the _marker.html.erb file
    }]

    @has_review = @bookings.any? { |booking| !booking.review.nil? }
  end

  def edit
  end

  def update
    if @flat.update(flat_params)
      redirect_to flat_path(@flat), notice: "Your flat has been succesfully updated"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @flat.destroy

    redirect_to flats_path, notice: "Flat was successfully destroyed"
  end

  # def users_flats
  # @flats = Flat.where(params[:current_user])
  # end

  private

  def set_flat
    @flat = Flat.find(params[:id])
    authorize @flat # pundit stuff
  end

  def flat_params
    params.require(:flat).permit(:name, :rooms, :price, :photo, :description, :address)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @flats = Flat.all
  end

  def my_flats
    @flats = Flat.where(user_id: current_user.id)
  end

  def my_bookings
    @bookings = Booking.where(user_id: current_user.id)
    @review = Review.new
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_booking, only: %i[new create]

  def new
    @review = Review.new
    authorize @review
  end

  def create
    @review = Review.new(review_params)
    @review.booking = @booking

    authorize @review # pundit stuff

    if @review.save!
      redirect_to flat_path(@booking.flat)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_booking
    @booking = Booking.find(params[:booking_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<div class="container">
  <h1 class="text-center mt-4">Edit your booking</h1>
  <div class="row justify-content-center">
    <div class="col-12 col-md-6 col-lg-4">
      <%= simple_form_for(@booking) do |f| %>
        <%= f.input :name %>
        <%= f.input :rooms %>
        <%= f.input :price %>
        <%= f.input :adults %>
        <%= f.input :children %>
        <%= f.submit class: "btn btn-primary" %>
      <% end %>
      <%= link_to "Cancel", booking_path(@booking), class: "btn btn-danger my-2" %>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<h1>Bookings#new</h1>
<p>Find me in app/views/bookings/new.html.erb</p>

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :rooms %>
  <%= f.input :price %>
  <%= f.input :description %>
  <%= f.input :address, input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"}, wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}} %>
  <%= f.input :photo, as: :file %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/flats/_info_window.html.erb
<h2><%= flat.name %></h2>
<p><%= flat.address %></p>

app/views/flats/edit.html.erb
<div class="container">
  <h1 class="text-center mt-4">Edit your property</h1>
  <div class="row justify-content-center">
    <div class="col-12 col-md-6 col-lg-4">
      <%= render "form", flat: @flat %>
      <%= link_to "Cancel", flat_path(@flat), class: "btn btn-danger my-2" %>
    </div>
  </div>
</div>

app/views/flats/index.html.erb
<div class="text-xl-center"'>
  <h1 class="text-center">View all flats</h1>
</div>
<div class="content">
  <div class="card-container">
    <% @flats.each do |flat| %>
      <%= link_to flat_path(flat), :class => "text-decoration-none" do %>
        <div class="card-flat align-items-stretch">
          <%= cl_image_tag flat.photo.key, :class => "img", crop: :fill if flat.photo.attached? %>
          <div class="card-flat-info">
            <div>
              <h2><%= flat.name %></h2>
            </div>
            <div class="d-flex justify-content-between">
              <div class="rooms">
                <i class="fa-solid fa-bed"></i>
                <span><%= flat.rooms %></span>
              </div>
              <div class="price">
                <i class="fa-solid fa-euro-sign"></i>
                <span><%= flat.price %>/night</span>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <%# !! Dealing with mapbox %>
  <div data-controller="map" data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>" data-map-markers-value="<%= @markers.to_json %>" data-map-zoom-value=10 id='map'></div>
</div>

app/views/flats/new.html.erb
<div class="container">
  <h1 class="text-center mt-4">List your property</h1>
  <div class="row justify-content-center">
    <div class="col-12 col-md-6 col-lg-4">
      <%= render "form", flat: @flat %>
      <%= link_to "Cancel", flats_path, class: "btn btn-danger my-2" %>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<div class="content">
  <div class="container-fluid">
    <% require "date" %>
    <% current_day = DateTime.current.to_date %>
    <div class="container margin-top-negative">
      <div class="row">
        <div class="mb-3">
          <%= link_to "Back", :back, class: "pink-btn" %>
        </div>
        <div class="col-sm-4 col-md-8">
          <br>
          <div class="flat-show-card">
            <h2><%= @flat.name %></h2>
            <p><%= @flat.address %></p>
          </div>
          <div class="flat-show-card">
            <%= cl_image_tag @flat.photo.key, width:700, crop: :fill, style: "border-radius: 15px;" if @flat.photo.attached?%>
          </div>
          <% if policy(@flat).edit? %>
            <%= link_to "Edit", edit_flat_path, class: "btn btn-warning" %>
          <% end %>
          <% if policy(@flat).destroy? %>
            <%= link_to "Delete your flat", flat_path(@flat), class: "btn btn-danger my-2", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
          <% end %>
          <br>
          <h3>Description</h3>
          <p><%= @flat.description %></p>
          <h3>Utilities</h3>
          <p><i class="fa-solid fa-bed"></i> -- <%= @flat.rooms %></p>
          <h3>Reviews</h3>
          <hr>
          <% if @has_review %>
            <% @bookings.each do |booking| %>
              <% if !booking.review.nil? %>
                <ul class="list-group list-unstyled">
                  <li>
                    <span class="fa-stack-1x" >
                      <%= icon('fa-solid', 'star' ) * booking.review&.rating + icon('fa-regular', 'star') * (5-booking.review&.rating) %>
                    </span>
                  </li>
                  <li>
                    <p><strong><%= current_user.first_name+" "+current_user.last_name %></strong></p>
                  </li>
                  <li>
                    <p><%= booking.review&.content %></p>
                  </li>
                  <hr>
                </ul>
              <% end %>
            <% end %>
          <% else %>
            <p>This property does not have any reviews yet.</p>
          <% end %>
          <h3>Location</h3>
          <% if @flat.geocoded? %>
            <div data-controller="map" data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>" data-map-markers-value="<%= @markers.to_json %>" data-map-zoom-value=15 id='show-map'></div>
          <% end %>
        </div>
        <div class="col-2">
          <% unless @flat.user == current_user %>
            <div class="card border-secondary mb-3" id="booking-form" style="width: 18rem;">
              <div class="bg-white rounded p-3">
                <h5 class="card-title text-center"><strong>Book this property</strong></h5>
                <h6 class="card-subtitle text-center"><%= @flat.price %>€ per night</h6>
                <%= simple_form_for [@flat, @booking], data: { controller: 'flatpickr' } do |f| %>
                  <%= f.input :start_date, as: :string, placeholder: "#{current_day}", input_html: { data: { flatpickr_target: "startTime" } } %>
                  <%= f.input :end_date, as: :string, placeholder: "#{current_day+3}", input_html: { data: { flatpickr_target: "endTime" } } %>
                  <div class="row">
                    <div class="col-sm-4">
                      <%= f.input :adults, as: :integer, label: 'Adults', placeholder: "1", input_html: { min: '1', value: f.object.adults || '1' } %>
                    </div>
                    <div class="col-sm-5">
                      <%= f.input :children, as: :integer, input_html: { min: '0', value: f.object.children || '0' } %>
                    </div>
                  </div>
                  <%= f.submit class: "blue-btn w-100 mb-2" %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirNBNCloneMs</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>
  <header>
    <%= render 'shared/navbar' %>
  </header>
  <div class="flex-wrapper">
    <body>
      <main>
        <%= render 'shared/flashes' %>
        <%= yield %>
      </main>
    </body>
    <footer>
      <%= render 'shared/footer' %>
    </footer>
  </div>
</html>

app/views/pages/home.html.erb
<div class="container">
  <h1 class="text-center my-2">Welcome!</h1>
  <p class="text-center">Find you favourite flat, and book anywhere around the world</p>
  <%= form_with url: flats_path, method: :get, class: "d-flex w-50 p-3 align-middle mx-auto" do %>
    <%= text_field_tag :query,params[:query], class: "form-control", placeholder: "Find a flat.." %>
    <%= submit_tag "Search", class: "light-blue-btn mx-3" %>
  <% end %>
  <div class="h-100 d-flex align-items-center justify-content-center">
    <%= link_to "View All", flats_path, class: "light-blue-btn" %>
  </div>
  <div class="travel-cards d-flex flex-row justify-content-between">
    <%= image_tag "travelling.svg" %>
    <%= image_tag "cabin.svg" %>
    <%= image_tag "photos.svg" %>
  </div>
</div>

app/views/pages/my_bookings.html.erb
<div class="container">
  <h1 class="text-center">My Bookings</h1>
  <div class="row">
    <div class="col-md-2">
      <%= cl_image_tag current_user.avatar.key, width: 150, height: 150, crop: :thumb, class: "rounded-circle" if current_user.avatar.attached? %>
      <h3><%= current_user.first_name %></h3>
      <p>Last login: <%= current_user.last_sign_in_at  %></p>
    </div>
    <div class="col-sm-6 col-md-10">
      <% @bookings.each do |booking| %>
        <div class="card-product my-3">
          <% if booking.flat.photo.attached? %>
            <%= cl_image_tag booking.flat.photo.key %>
          <% else %>
            <img src="https://liftlearning.com/wp-content/uploads/2020/09/default-image.png" />
          <% end %>
          <div class="card-product-infos">
            <h2><%= booking.flat.name %></h2>
            <p><strong>Check in: </strong><%= booking.start_date %> &nbsp; <strong>Check out: </strong> <%= booking.end_date %></p>
            <% no_of_nights = booking.end_date > booking.start_date ? booking.end_date - booking.start_date : 1 %>
            <% no_of_guests = booking.adults + booking.children %>
            <% cost = booking.flat.price * no_of_nights.to_i * no_of_guests.to_i %>
            <p><strong>Number of nights: </strong> <%= no_of_nights.to_i %> &nbsp; <strong>Estimated cost: </strong> <%= '€'+number_with_precision(cost, precision: 2) %></p>
            <div class="my-2">
              <%= link_to "Cancel Reservation", booking_path(booking), class: "blue-btn", data: { turbo_method: :delete, turbo_confirm: "You are cancelling your booking reservation at #{booking.flat.name}" }  %>
              <%= link_to "Write a review", new_booking_review_path(booking), class:"light-blue-btn" %>
              <%= link_to "View Flat", flat_path(booking.flat), class:"pink-btn" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/my_flats.html.erb
<div class="container">
  <h1 class="text-center">My Flats</h1>
  <div class="row">
    <div class="col-md-2">
      <%= cl_image_tag current_user.avatar.key, width: 150, height: 150, crop: :thumb, class: "rounded-circle" %>
      <h3><%= current_user.first_name %></h3>
      <p>Last login: <%= current_user.last_sign_in_at  %></p>
    </div>
    <div class="col-sm-6 col-md-10">
      <% @flats.each do |flat| %>
        <div class="card-product my-3">
          <% if flat.photo.attached? %>
            <%= cl_image_tag flat.photo.key %>
          <% else %>
            <img src="https://liftlearning.com/wp-content/uploads/2020/09/default-image.png" />
          <% end %>
          <div class="card-product-infos">
            <h2 class="my-2"><%= flat.name %></h2>
            <i class="fa-solid fa-bed"></i>
            <span><%= flat.rooms %></span>
            <i class="fa-solid fa-euro-sign"></i>
            <span><%= flat.price %></span>
            <div class="my-4">
              <% if policy(flat).edit? %>
                <%= link_to "Edit", edit_flat_path(flat), class: "light-blue-btn" %>
              <% end %>
              <% if policy(flat).destroy? %>
                <%= link_to "Delete your flat", flat_path(flat), class: "blue-btn", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
              <% end %>
              <%= link_to "View Flat", flat_path(flat), class: "pink-btn" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/new.html.erb
<div class="container">
  <h1 class="text-center mt-4">Add new list</h1>
  <div class="row justify-content-center">
    <div class="col-12 col-md-6 col-lg-4">
     <%= simple_form_for(@flat) do |f| %>
        <%= f.input :name %>
        <%= f.input :rooms %>
        <%= f.input :price %> €
        <%= f.submit class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <h1><%= "Review your stay at #{@booking.flat.name}"%></h1>
  <%= simple_form_for [@booking, @review] do |f| %>
    <%= f.input :rating, collection: (1..5).to_a, label: "Rate your experience", input_html: {data: {controller: "star-rating"}} %>
    <%= f.input :content %>
    <%= f.submit "Submit review", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-4" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show m-4" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <% if user_signed_in? %>
    <h4 class="text-success">Welcome back, <%= current_user.first_name %>!</h4>
  <% end %>
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_marker.html.erb
<%#!! if we want to use a marker uncomment the second line and fix the end of the line%>
<%# <%= image_tag "(add image namefile)", height: 30, width: 30, alt: "Logo" %>
<%#!! if we want to add more info to the marker, fix line 5, at the end%>
<%# <div class="badge rounded-pill bg-primary fs-6"> %>
<%# <%= flat.name %>
<%# </div> %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag("bob.jpg") %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= link_to ('<i class="fa-solid fa-magnifying-glass"></i>').html_safe, root_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= cl_image_tag current_user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  if current_user.avatar.attached?%>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "New flat", new_flat_path, class: "dropdown-item" %>
              <%= link_to "My flats", my_flats_path, class: "dropdown-item" %>
              <%= link_to "My bookings", my_bookings_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>